name: Build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to github container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Add .env to app
        run: |
          cd app
          echo "AWS_REGION={{ var.AWS_REGION }}" >> .env
          echo "SES_FROM_EMAIL={{ var.SES_FROM_EMAIL }}" >> .env
          echo "SES_TO_EMAIL={{ var.SES_TO_EMAIL }}" >> .env
          echo "AWS_ACCESS_KEY_ID={{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY={{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env

      - name: Build and Push Docker image for application
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}